"""
AlgoVoi CeX (Computer Exchange) Payment Adapter

CeX has no public Seller API, webhook system, or Seller Hub portal.
The only public CeX API is a read-only catalogue lookup API — it has
no order management or outbound events.

This adapter operates in BYPASS MODE ONLY:

  - Your backend (or a CeX trade notification email parser) POSTs order
    data directly to AlgoVoi with Authorization: Bearer <webhook_secret>
  - AlgoVoi creates a hosted checkout link
  - You share the checkout URL with the buyer via CeX messaging or email
  - There is NO automated webhook path and NO fulfill_order method

NOTE: CeX has no public API. Share checkout_url with buyer manually.

CeX catalogue API (read-only, not used here):
  https://wss2.cex.{cc}.webuy.io/v3/

Version: 1.0.0

AlgoVoi docs: https://github.com/chopmob-cloud/AlgoVoi-Platform-Adapters
Licensed under the Business Source License 1.1 — see LICENSE for details.
"""

# PROVISIONAL: This adapter has not been end-to-end tested against a live
# platform environment. API details are based on official documentation and
# community sources. Verify against your platform's current API before
# production use. See README.md for status.

from __future__ import annotations

import hashlib
import hmac
import json
import re
import ssl
from typing import Any, Optional
from urllib.parse import quote
from urllib.request import Request, urlopen
from urllib.error import URLError

__version__ = "1.0.0"

HOSTED_NETWORKS = {"algorand_mainnet", "voi_mainnet", "hedera_mainnet", "stellar_mainnet"}

CHAIN_LABELS = {
    "algorand_mainnet": "USDC on Algorand",
    "voi_mainnet": "aUSDC on VOI",
    "hedera_mainnet": "USDC on Hedera",
    "stellar_mainnet": "USDC on Stellar",
}


class CexAlgoVoi:
    """CeX (Computer Exchange) bypass-mode + AlgoVoi payment adapter."""

    def __init__(
        self,
        api_base: str = "https://api1.ilovechicken.co.uk",
        api_key: str = "",
        tenant_id: str = "",
        webhook_secret: str = "",
        default_network: str = "algorand_mainnet",
        base_currency: str = "GBP",
        timeout: int = 30,
    ):
        self.api_base = api_base.rstrip("/")
        self.api_key = api_key
        self.tenant_id = tenant_id
        self.webhook_secret = webhook_secret
        self.default_network = default_network
        self.base_currency = base_currency
        self.timeout = timeout
        self._ssl = ssl.create_default_context()

    # ── Webhook / Bypass Verification ────────────────────────────────────

    def verify_webhook(self, raw_body: bytes, signature: str) -> Optional[dict]:
        """
        Verify an internal AlgoVoi bypass POST via X-Cex-Signature header.

        Since CeX has no outbound webhook, the signature is an HMAC-SHA256
        hex digest generated by your own backend for internal authentication.

        Args:
            raw_body:  Raw POST body as bytes
            signature: X-Cex-Signature header value (HMAC-SHA256 hex)

        Returns:
            Parsed payload dict, or None if verification fails
        """
        if not self.webhook_secret:
            return None

        expected = hmac.new(
            self.webhook_secret.encode(),
            raw_body,
            hashlib.sha256,
        ).hexdigest()

        if not hmac.compare_digest(expected, signature):
            return None

        try:
            return json.loads(raw_body)
        except json.JSONDecodeError:
            return None

    # ── Order Parsing ─────────────────────────────────────────────────────

    def parse_bypass_order(self, data: dict) -> Optional[dict]:
        """
        Parse a manually POSTed bypass order payload.

        Expected format (from the CeX bypass POST endpoint):
        {
            "event": "order.created",
            "order": {
                "order_id": "CEX-123456",
                "currency": "GBP",
                "totalPrice": 49.99,
                "items": [
                    {"box_id": "BX123", "description": "...", "quantity": 1, "unit_price": "49.99"}
                ]
            }
        }

        Args:
            data: Parsed JSON from the bypass POST body

        Returns:
            dict with order_id, amount, currency, description — or None
        """
        try:
            event = data.get("event", "")
            # Accept order.created and empty event (legacy)
            if event and event not in ("order.created", "order.updated"):
                return None

            order = data.get("order", data)
            order_id = str(order.get("order_id", order.get("id", "")))
            if not order_id:
                return None

            # CeX uses totalPrice (float) or items sum
            amount_raw = order.get("totalPrice", order.get("total_price", None))
            if amount_raw is not None:
                amount = float(amount_raw)
            else:
                # Sum items
                items = order.get("items", [])
                amount = sum(
                    int(item.get("quantity", 1)) * float(item.get("unit_price", 0))
                    for item in items
                )

            currency = str(order.get("currency", self.base_currency)).upper()

            # Build description from items
            items = order.get("items", [])
            if items:
                description = "; ".join(
                    str(item.get("description", item.get("box_id", "")))
                    for item in items
                    if item.get("description") or item.get("box_id")
                )
            else:
                description = str(order.get("description", ""))

            return {
                "order_id": order_id,
                "amount": round(amount, 2),
                "currency": currency,
                "description": description,
                "event": event,
            }
        except (KeyError, TypeError, ValueError, AttributeError):
            return None

    # ── Checkout ─────────────────────────────────────────────────────────

    def process_order(
        self,
        order_id: str,
        amount: float,
        currency: Optional[str] = None,
        network: Optional[str] = None,
        label: Optional[str] = None,
        redirect_url: str = "",
    ) -> Optional[dict]:
        """
        Create an AlgoVoi payment link for a CeX order.

        Returns the checkout_url which the merchant must share with the
        buyer manually via CeX messaging or email.

        NOTE: CeX has no public API — there is no fulfill_order method.
        Share checkout_url with buyer manually after calling this method.

        Args:
            order_id:     CeX order ID
            amount:       Order total
            currency:     ISO currency code (defaults to base_currency)
            network:      Preferred network (defaults to default_network)
            label:        Payment label
            redirect_url: Return URL after payment (optional)

        Returns:
            dict with checkout_url, token, chain, amount_microunits — or None
        """
        if not network or network not in HOSTED_NETWORKS:
            network = self.default_network
        if not currency:
            currency = self.base_currency
        if not label:
            label = f"CeX Order #{order_id}"

        payload: dict[str, Any] = {
            "amount": round(amount, 2),
            "currency": currency.upper(),
            "label": label,
            "preferred_network": network,
            "reference": order_id,
        }
        if redirect_url:
            payload["redirect_url"] = redirect_url
            payload["expires_in_seconds"] = 1800

        resp = self._post("/v1/payment-links", payload)
        if not resp or not resp.get("checkout_url"):
            return None

        token = ""
        m = re.search(r"/checkout/([A-Za-z0-9_-]+)$", resp["checkout_url"])
        if m:
            token = m.group(1)

        return {
            "checkout_url": resp["checkout_url"],
            "token": token,
            "chain": resp.get("chain", "algorand-mainnet"),
            "amount_microunits": int(resp.get("amount_microunits", 0)),
            "order_id": order_id,
        }

    def verify_payment(self, token: str) -> bool:
        """
        Check if a payment has been completed.

        Args:
            token: AlgoVoi checkout token

        Returns:
            True only if the API confirms payment is complete
        """
        if not token:
            return False
        tx_id = token
        if len(tx_id) > 200:
            return False

        url = f"{self.api_base}/checkout/{quote(token, safe='')}"
        if not url.startswith("https://"):
            return False
        try:
            req = Request(url, method="GET")
            with urlopen(req, timeout=15, context=self._ssl) as resp:  # nosec B310
                if resp.status != 200:
                    return False
                data = json.loads(resp.read())
                return data.get("status") in ("paid", "completed", "confirmed")
        except (URLError, json.JSONDecodeError, OSError):
            return False

    # ── Flask Handler ─────────────────────────────────────────────────────

    def flask_webhook_handler(self):
        """
        Returns a Flask view function for the CeX bypass endpoint.

        Accepts internal POSTs from your own backend with HMAC-SHA256
        authentication via X-Cex-Signature header.

        Usage:
            app.add_url_rule('/webhook/cex',
                view_func=adapter.flask_webhook_handler(), methods=['POST'])
        """
        adapter = self

        def handler():
            from flask import request, jsonify

            raw_body = request.get_data()
            signature = request.headers.get("X-Cex-Signature", "")

            payload = adapter.verify_webhook(raw_body, signature)
            if payload is None:
                return jsonify(error="Unauthorized"), 401

            order = adapter.parse_bypass_order(payload)
            if not order:
                return jsonify(received=True, skipped="not a parseable order")

            result = adapter.process_order(
                order_id=order["order_id"],
                amount=order["amount"],
                currency=order["currency"],
                label=order["description"] or None,
            )

            if not result:
                return jsonify(error="Could not create payment link"), 502

            return jsonify(
                received=True,
                order_id=order["order_id"],
                checkout_url=result["checkout_url"],
                chain=result["chain"],
                note="CeX has no public API. Share checkout_url with buyer manually.",
            )

        return handler

    # ── Internal ─────────────────────────────────────────────────────────

    def _post(self, path: str, data: dict) -> Optional[dict]:
        if not self.api_base.startswith("https://"):
            return None
        body = json.dumps(data).encode()
        req = Request(
            f"{self.api_base}{path}",
            data=body,
            method="POST",
            headers={
                "Content-Type": "application/json",
                "Authorization": f"Bearer {self.api_key}",
                "X-Tenant-Id": self.tenant_id,
            },
        )
        try:
            with urlopen(req, timeout=self.timeout, context=self._ssl) as resp:  # nosec B310
                if resp.status < 200 or resp.status >= 300:
                    return None
                return json.loads(resp.read())
        except (URLError, json.JSONDecodeError, OSError):
            return None
